added more tests about basic scorsh setup

diff --git a/test/scorsh_functions b/test/scorsh_functions
--- a/test/scorsh_functions
+++ b/test/scorsh_functions
@@ -41,6 +41,25 @@ check(){
 }
 
 ## func
+check_fatal(){
+    EXPR="$1"
+    TEST_NAME="$2"
+    TEST_SECTION="$3"
+
+    TOT_TESTS=$((${TOT_TESTS} + 1))
+    
+    ##echo "EXPR: ${EXPR}"
+    if  $(echo ${EXPR}) ; then 
+        passed ${TEST_NAME} ${TEST_SECTION}
+    else
+        failed ${TEST_NAME} ${TEST_SECTION}
+        echo "Fatal test failed -- Aborting"
+        exit 1
+    fi
+}
+
+
+## func
 report_results(){
     
     echo -n "TOTAL_TESTS: ${TOT_TESTS} -- "
diff --git a/test/scorsh_testsuite b/test/scorsh_testsuite
--- a/test/scorsh_testsuite
+++ b/test/scorsh_testsuite
@@ -22,10 +22,10 @@ trap cleanup 0 HUP INT TRAP TERM QUIT
 ## func
 cleanup(){
     ## do stuff here
-    rm -rf ${SCORSH_REPO}
-    rm -rf ${SCORSH_APP}
-    rm -rf ${REMOTE_REPO}
-    rm -rf ${LOCAL_REPO}
+    # rm -rf ${SCORSH_REPO}
+    # rm -rf ${SCORSH_APP}
+    # rm -rf ${REMOTE_REPO}
+    # rm -rf ${LOCAL_REPO}
     
     echo "Exiting..."
 }
@@ -37,6 +37,10 @@ run_tests(){
         export PASSED_TESTS FAILED_TESTS TOT_TESTS
         echo "\033[4;7;36m-+-+- running tests in $t -+-+-\033[0m"
         $t
+        if [ $? -ne 0 ]; then
+            echo "test $t aborted unexpectedly. Aborting"
+            exit 2
+        fi
         eval $(cat ${STATUS_FILE})
         echo "\033[35m-------------------------------------------------------------\033[0m"
         
@@ -51,6 +55,8 @@ export SCORSH_URL SCORSH_REPO SCORSH_APP REMOTE_REPO LOCAL_REPO
 PASSED_TESTS=0
 FAILED_TESTS=0
 TOT_TESTS=0
+
+rm ${STATUS_FILE}
 
 run_tests
 
